"""Initial migration

Revision ID: 51654a8d3c41
Revises: 
Create Date: 2025-01-10 15:52:12.560411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "51654a8d3c41"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_load",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cpu_load", sa.Float(), nullable=False),
        sa.Column("ram_load", sa.Float(), nullable=False),
        sa.Column("disk_load", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_load_id"), "system_load", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_load_id"), table_name="system_load")
    op.drop_table("system_load")
    # ### end Alembic commands ###
